### ISSUE TITLE
Trouvé mes enceintes mais internal server error

### ISSUE THREAD

**Issue by jmarkelion** [lucguinchard/plugin-Yamaha-musiccast#24]
## Environnement:

* **Version Jeedom** :v4.0.45
* **Plateforme** :
* **Version du Plugin plugin-YamahaMusiccast** :

## Description

Bonjour,

Un grand merci pour le développement de ce plugin, j'ai pu l'installer ce matin. Il me mettait internal server error quand j'ai souhaité rajouter mes enceintes automatiquement, pourtant en raffraichissant quelle joie de les voir.
![image](https://user-images.githubusercontent.com/62931052/78003055-62bae600-7338-11ea-9083-e3eb4b776bb9.png)

Cependant, quand je veux les afficher dans mon dashboard ou que je les cherche dans équipement (dans mon design), je ne les trouver et j'ai le message suivant : 
![image](https://user-images.githubusercontent.com/62931052/78003130-7f571e00-7338-11ea-87a3-1cf3762ec318.png)

Merci en tout cas, je commençais à désespérer de ces enceintes que je trouve top niveau son mais dont le retard technologique m'ennuyait.

**Comment by lucguinchard** [comment]
Résolu avec le commit14b1b6d52aeb575329226f7814851c482a0ad432
