### ISSUE TITLE
Favoris DAB et FM

### ISSUE THREAD

**Issue by zz2021top** [lucguinchard/plugin-Yamaha-musiccast#39]
Bonjour,
j'avais l'ancien plugins Musiccast qui ne fonctionne malheureusement plus. Je suis absolument ravi du plugin que vous avez créé. Il fonctionne bien sur mon RXAS710D. J'aurais cependant une suggestion. Il ne voit pas mes radios favorites (FM et DAB), il voit cependant bien mes radios internet.
Si vous avez besoins d'infos supplémentaires, j'essayerai de vous aider avec mes moyens limités.
Encore merci pour ce gros travail

**Comment by lucguinchard** [comment]
Salut @zz2021top,
Est-ce que c'est bon pour les favories DAB et FM ?
Bon dimanche.

**Comment by zz2021top** [comment]
Bonjour Luc,
désolé pour le délai. Cela fonctionne très bien, merci beaucoup.
C'est dommage que pour la FM Yamaha utilise la fréquence et pas le nom RDS de la station. Le plugin que tu as fait n'y peut rien.
J'ai vu que tu as aussi fait la gestion des scènes :)
Super travail
zz
