### ISSUE TITLE
la commande power_state est toujours à 'on'

### ISSUE THREAD

**Issue by FModolo** [lucguinchard/plugin-Yamaha-musiccast#40]
Bonjour Luc,

Je me retrouve depuis quelque temps avec la commande power_state qui ne se met plus à jour. Du coup le widget ne permet plus que d'éteindre l'appareil mais pas de l'allumer. C'est aussi embêtant au niveau de mes scénarios. J'ai ce problème sur mes 2 WX-030 et mon ampli Yamaha.

Les commandes d'action power_on et power_off fonctionnent parfaitement bien quant à elles.

J'ai fait une tentative de suppression du cache Jeedom pour forcer la mise à jour de la commande info power_state, mais cela n'a pas fonctionné. 

J'utilise la branche master de ton plugin sur une version v4.1.22 de Jeedom avec Debian 10 à jour.

Si tu as besoin de plus d'info (j'ai mis les logs en niveau debug) n'hésite pas à me les demander.

Cordialement,
Franck

EDIT:
Je viens de faire une synchronisation des équipements, et maintenant tout le monde est passé en stand_by, donc même problème mais sur un autre état maintenant.

**Comment by lucguinchard** [comment]
Bonjour,

Très bizarre, j'ai pas du tout ce problème. Je te propose de réinstaller les sources dans Jeedom : Centre de mise à jour → Réinstaller sur la ligne du plugin.

Si cela continu, il faudra me donner plus d'info log ou un accès.

Bonne journée.

**Comment by FModolo** [comment]
J'ai testé la réinstallation, mais sans succès. C'est extrêmement curieux, la commande prend l'état des l'enceintes au moment ou je fais une resynchronisation, et ensuite elle ne se met plus à jour. Si tu veux on peut faire une séance en remote pour que tu puisse constater le soucis directement.

**Comment by lucguinchard** [comment]
OK pour une séance en remote. Tu as un mail/phone pour que je puisse te contacter ?

**Comment by FModolo** [comment]
Bonjour Luc et merci. Je t'ai envoyé mes coordonnées en PM sur le forum Jeedom.

**Comment by FModolo** [comment]
Bonjour Luc,

Je viens de rentrer de congés.

Après la maj du plugin, un rechargement de la page en vidant le cache, le problème est toujours présent, mais avec une différence. Lorque j'intérroge la commande power_state, j'obiens ce résulatat -> Résultat de la commande : unreachable

Je reste à ta disposition,
Franck

**Comment by lucguinchard** [comment]
Si la réponse est `unreachable` c'est que ton appareil  n'arrive pas a être joint à partir de ton Jeedom.
Est-ce qu'il se trouve dans le même réseau ? C'est quoi l'ip du ton Jeedom et celui du ton musiccast ?

**Comment by FModolo** [comment]
C'est étonnant, car les commandes power_on et power_off fonctionnent bien que je les exécute.

**Comment by lucguinchard** [comment]
Est-ce que tu as des logs mise à jour depuis la dernière fois ?

**Comment by lucguinchard** [comment]
Est-ce que le deamon du plugin est bien lancé ? C'est lui qui met à jour les états des appareils.

**Comment by FModolo** [comment]
Oui je l'ai même redémarré et refait un essai.

**Comment by FModolo** [comment]
Je t'informe que le dernier patch que tu as fait corrige le problème de la maj de l'état power_state. Je ne rencontre plus de soucis et du coup les widgets refonctionne correctement. Merci :)
