### ISSUE TITLE
Erreur 500 lors de la recherche des équipements

### ISSUE THREAD

**Issue by Gis70** [lucguinchard/plugin-Yamaha-musiccast#41]
SUr Jeedom v4 

```
[Wed May 26 22:00:54.585944 2021] [php7:error] [pid 31134] [client fe80::3c14:bf] PHP Fatal error:  Uncaught Error: Call to a member function setConfiguration() on bool in /var/www/html/plugins/YamahaMusiccast/core/class/YamahaMusiccast.class.php:1709
Stack trace:
#0 /var/www/html/plugins/YamahaMusiccast/core/class/YamahaMusiccast.class.php(969): YamahaMusiccast::callSystemNameText(Array, '192.168.0.51')
#1 /var/www/html/plugins/YamahaMusiccast/core/class/YamahaMusiccast.class.php(463): YamahaMusiccast::saveDeviceIp('192.168.0.51')
#2 /var/www/html/plugins/YamahaMusiccast/core/ajax/YamahaMusiccast.ajax.php(41): YamahaMusiccast::searchAndSaveDeviceList()
#3 {main}
thrown in /var/www/html/plugins/YamahaMusiccast/core/class/YamahaMusiccast.class.php on line 1709, referer: http://jeedom/index.php?v=d&m=YamahaMusiccast&p=YamahaMusiccast&id=YamahaMusiccast
Wed May 26 22:01:46 2021 (7547): Error Cannot kill process 19326: Success!
```

**Comment by lucguinchard** [comment]
Salut, 

La fonction `setConfiguration` est sur la la ligne 1710 et pas 1709. Est-ce que tu as bien la dernière version ? essaye de réinstaller dans le `Centre de mise` à jour de Jeedom.

Merci à toi.
Luc

**Comment by Gis70** [comment]
Salut ça a disparu en relançant le deamon. Par contre mes enceintes ne sont pas trouvées, j'ai seulement le HC. Dans la FAQ on parle d'un mode ajout via IP mais je ne vois que la recherche auto ?

**Comment by lucguinchard** [comment]
Salut, Il faut parfois faire plusieurs fois la recherche auto pour qu'il trouve toutes les enceintes.
En faite l'ajout par ip n'existe plus depuis qu'il y a la recherche auto. Elle n'existe plus car cela pose des problèmes lors de réseau différent.

Tu as encore l'erreur 500 ?

**Comment by Gis70** [comment]
Salut, j'ai toujours l'erreur 500 :   
De plus mes 3 autres enceintes hors 192.168.0.51 qui est mon HC ne sont pas toruvées alors que dans le log elles apparaissent.

![image](https://user-images.githubusercontent.com/16589132/120886199-0b27a280-c5ed-11eb-9928-18183cb1b438.png)


`[Sat Jun 05 10:57:23.860662 2021] [php7:error] [pid 22263] [client 192.168.0.64:53147] PHP Fatal error:  Uncaught Error: Call to a member function setConfiguration() on bool in /var/www/html/plugins/YamahaMusiccast/core/class/YamahaMusiccast.class.php:1703
Stack trace:
#0 /var/www/html/plugins/YamahaMusiccast/core/class/YamahaMusiccast.class.php(970): YamahaMusiccast::callSystemNameText(Array, '192.168.0.51')
#1 /var/www/html/plugins/YamahaMusiccast/core/class/YamahaMusiccast.class.php(464): YamahaMusiccast::saveDeviceIp('192.168.0.51')
#2 /var/www/html/plugins/YamahaMusiccast/core/ajax/YamahaMusiccast.ajax.php(41): YamahaMusiccast::searchAndSaveDeviceList()
#3 {main}
  thrown in /var/www/html/plugins/YamahaMusiccast/core/class/YamahaMusiccast.class.php on line 1703, referer: http://jeedom/index.php?v=d&m=YamahaMusiccast&p=YamahaMusiccast
`

**Comment by lucguinchard** [comment]
Je pense qu'il y a un soucis avec les appareils multi-zones. n'en n'ayant pas, il m'est compliqué de reproduire. Je réfléchit à cela.
Étant donné que cela plante avec ton ampli, il ne fini pas la boucle et n’analyse pas les autres enceintes.

**Comment by lucguinchard** [comment]
Salut @Gis70, Suite aux différentes mise à jour : Est-ce que ce sujet est résolu ?

**Comment by Gis70** [comment]
Salut,

Je vais faire la dernière mise à jour et je te tiens au courant. Cordialement.

**Comment by Gis70** [comment]
c'est parfait tout a été trouvé merci Luc

**Comment by lucguinchard** [comment]
bugfix : https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/f8d2370c8c549d42e58291465f9281d0681a62ec
