### ISSUE TITLE
 Invalid Parameter (Out of range, invalid characters etc.

### ISSUE THREAD

**Issue by Gis70** [lucguinchard/plugin-Yamaha-musiccast#42]
Salut Luc, j'ai ça depuis toujours avec mon HC RXV485 sur le plugin. Je crois que tu avais jeté un oeil à l'époque.

Resultat appel http://192.168.0.51/YamahaExtendedControl/v1/tuner/getPresetInfo?band=fm : 4 - Invalid Parameter (Out of range, invalid characters etc.

Si je fais ça dans un browser j'ai en retour : `{"response_code":4}`

**Comment by lucguinchard** [comment]
Le code `{"response_code":4}` est bien un code de type `Invalid Parameter`. La question c'est de savoir pourquoi ton RXV485 retourne cela.

**Comment by Gis70** [comment]
Je crois que cette trame n'a jamais fonctionné, tu n'as pas de Home Cinema toi ? 

`http://192.168.0.51/YamahaExtendedControl/v1/tuner/getPlayInfo`

renvoi :  

`{"response_code":0,"band":"fm","auto_scan":false,"am":{"preset":0,"freq":1071,"tuned":false},"fm":{"preset":3,"freq":93400,"tuned":true,"audio_mode":"mono"},"rds":{"program_type":"","program_service":"  RTL2  ","radio_text_a":"","radio_text_b":""}}`

Je sais pas si tu peux en tirer qqch pour remplacer l'autre commande qui marche pas si c'est un Home Cinema

**Comment by lucguinchard** [comment]
Salut,
On peut faire le point ensemble sur ton problème ? Une prise à distance ?
Bonne semaine.

**Comment by Gis70** [comment]
Salut, cette semaine je suis pas sûr, je te contacte à l'occase sur Discord si je te vois.

**Comment by Gis70** [comment]
Salut, j'ai retrouvé nos échanges sur Discord, fm ou band n'existe pas sur mon HC. En revanche j'ai common qui retourne : 

`http://192.168.0.51/YamahaExtendedControl/v1/tuner/getPresetInfo?band=common`

`{"response_code":0,"preset_info":[{"band":"fm","number":98400,"hd_program":0,"text":" VIRGIN "},{"band":"fm","number":100000,"hd_program":0,"text":"   FUN  "},{"band":"fm","number":93400,"hd_program":0,"text":"  RTL2  "},{"band":"fm","number":93400,"hd_program":0,"text":"  RTL2  "},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""},{"band":"unknown","number":0,"hd_program":0,"text":""}],"func_list":["clear","move"]}`

**Comment by lucguinchard** [comment]
Oui tout à fait, j'ai fait des modifications en ce sens. Tu as toujours les soucis ?

Si oui, il faut qu'on se fasse une prise à distance.

**Comment by lucguinchard** [comment]
Des nouvelles de cette erreur ? @Gis70  ?

**Comment by Gis70** [comment]
Oui s'était toujours présent avec la beta dispo la semaine dernière. Du coup c'est lié aux home cinéma ? A des modèles particuliers ?

**Comment by lucguinchard** [comment]
Il faut qu'on se fasse une prise à distance ;) Je suis dispo toute la semaine prochaine.
