### ISSUE TITLE
Erreur Javascript

### ISSUE THREAD

**Issue by zz2021top** [lucguinchard/plugin-Yamaha-musiccast#43]
Avant de valider la demande, merci de vérifier qu’il n’y est pas déjà une demande pour la même icône.
Bonjour,
merci beaucoup pour la mise a jour :) :)
Il y a cependant une erreur java lorsque j'affiche le plugins sur la page jeedom. Sur la zone principale uniquement (si je la masque et que je laisse la zone 2, pas de problème). Le message d'erreur est le suivant
http://xxx.xxx.x.xxx/index.php?v=d&p=dashboard
Ligne 36
Uncaught TypeError: Cannot read property 'replace' of undefined
Encore merci
Cdt
zz

**Comment by lucguinchard** [comment]
bugfix : https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/f8d2370c8c549d42e58291465f9281d0681a62ec
