### ISSUE TITLE
liste de toute les commandes de API

### ISSUE THREAD

**Issue by ibasaw** [lucguinchard/plugin-Yamaha-musiccast#46]
hello,

Je fais mon browser web php 7 sur symfony5, pour commander mon AVR, le tout sur net_usb server uniquement.
il s'agit d'un exercice perso. Il ne s'agit pas d'en faire un projet public, ou un bundle.

Je lis le tout sur mon AVR via DLNA, desservi par plex server, sur IP fixe, serveur et AVR.

j'ai à ma disposition 3 fichiers de documentations:

- Yamaha MusicCast HTTP simplified API for ControlSystems.pdf
- YXC_API_Spec_Advanced.pdf
- YXC_API_Spec_Basic.pdf

Dans ses documentations, je ne vois pas d'infos sur comment récupérer le chemin complet vers le fichier lu, la piste courante
J'ai besoin du chemin physique sur le serveur, pour lire les metadatas à la volée.(plex bug sur les metadatas).

Je recherche donc une documentation complète et a jour.

Aujourd'hui, je n'arrive pas a reset la queue (liste de lecture, j utilise que ca) (ca fonctionne quand ca veut), il retourne, response code 0, mais le liste est toujours pleine ...

je n'arrive pas a avoir les infos de track détaille => temps du track global, combien dure une chanson.

je n'arrive pas a faire la correspondance entre la track lu sur AVR, et la track physique sur plex server. Aucun ID me permet de faire la correspondance...

je n'arrive pas a utiliser socket, il me dit erreur de connexion. je ne sais donc pas quels sont les informations disponible en retour temps réel.

le previous track ne fonctionne pas, il recommence la chanson en cours, au lieu de lire la chanson précédente => bug ?

je n'arrive pas a avoir un contact fiable pour poser mes questions sur cette api, un support ticket, un email, chat, forum, slack ?

un peu d'aide serait la bienvenue :)

++

**Comment by lucguinchard** [comment]
Bonjour,

>je n'arrive pas a avoir un contact fiable pour poser mes questions sur cette api, un support ticket, un email, chat, forum, slack ?

J'ai uniquement à ma possession les trois documents (2018) que tu mentionnes. Je n'ai aucun contact chez Yamaha. D'ailleurs aucun site chez eux ne parle de cette API. J'imagine que les 3 documents sont des fuites ; et donc L’API Yamaha a été réalisé pour leur application android et iOS. En tout cas ces documents décrivent bien l'ensemble des méthodes utilisables par cette même application.

J'ai pas beaucoup travaillé avec les méthodes de l'entrée `server`. Mais si tu veux réaliser des choses que leur application ne fait pas, je pense que tu ne pourras pas le réaliser.

>Dans ses documentations, je ne vois pas d'infos sur comment récupérer le chemin complet vers le fichier lu, la piste courante
J'ai besoin du chemin physique sur le serveur, pour lire les metadatas à la volée.(plex bug sur les metadatas).

>je n'arrive pas a avoir les infos de track détaille => temps du track global, combien dure une chanson.

Je ne voie pas pourquoi L’API te donnerai accès à un chemin complet. L'application mobile n'en a pas besoin.
Concernant les infos de la piste que ce soit en UPNP/DLNA ou sur Spootify.  L'application mobile ne les affiche pas non plus. Je ne sais même pas si l'ampli a (ou pourrait avoir) ces informations.

> je n'arrive pas a utiliser socket, il me dit erreur de connexion. je ne sais donc pas quels sont les informations disponible en retour temps réel.

Le code du socket est disponible dans le dépôt. Je te propose de le regarder.

> le previous track ne fonctionne pas, il recommence la chanson en cours, au lieu de lire la chanson précédente => bug ?

Quand je fait précédent avec une télécommande (platine CD) ou une application (spootify, deezer) quand je clique sur `previous track` il revient toujours au début de la piste. Et faire une double clique pour retourner à la piste précédente.

Bonne journée

**Comment by ibasaw** [comment]
merci pour ces réponses :)
