### ISSUE TITLE
Changement d'IP

### ISSUE THREAD

**Issue by kadmon77** [lucguinchard/plugin-Yamaha-musiccast#47]
Depuis quelques temps, certaines enceintes s'inversent sans raisons apparentes. Serait-il possible d'avoir accès au champs d'IP (actuellement grisé) pour corriger manuellement l'IP et diriger le son vers la bonne enceinte ?

**Comment by lucguinchard** [comment]
Alors il est conseillé (voir même obligatoire) de fixer les ips pour ces appareils. Que ce soit pour le bon déroulement du multi-room et aussi de l'utilisation des applications mobiles ou jeedom. Est-ce qu'il est possible de me dire pourquoi `vos certaines enceintes s'inversent sans raisons apparentes`. Les IPs sont interchangées ou ils prennent de nouvelles IPs ?

Par contre, je peux comprendre qu'on doit pouvoir refixer des nouvelles IPs aux appareils. Je vais donc y réfléchir en ce sens.

**Comment by kadmon77** [comment]
Je n'ai aucune idée du pourquoi. Elles se sont interchangées entre deux enceintes. Ça n'est pas la première fois que ça arrive et toujours entre enceintes, les autres IP ne bougent pas pour les autres objets connectés. -------- Message original --------De : Luc Guinchard ***@***.***>Date : dim. 3 oct. 2021 à 10:39À : lucguinchard/plugin-Yamaha-musiccast ***@***.***>Cc : kadmon77 ***@***.***>, Author ***@***.***>Objet : Re: [lucguinchard/plugin-Yamaha-musiccast] Changement d'IP (#47)

Alors il est conseillé (voir même obligatoire) de fixer les ips pour ces appareils. Que ce soit pour le bon déroulement du multi-room et aussi de l'utilisation des applications mobiles ou jeedom. Est-ce qu'il est possible de me dire pourquoi vos certaines enceintes s'inversent sans raisons apparentes. Les IPs sont interchangées ou ils prennent de nouvelles IPs ?

Par contre, je peux comprendre qu'on doit pouvoir refixer des nouvelles IPs aux appareils. Je vais donc y réfléchir en ce sens.

**Comment by lucguinchard** [comment]
Est-ce que tes IPs sont fixées par le DHCP ? Ensuite si les IPs sont interchangées : les modifier pourrais provoquer d'autres erreurs car les appareils n'ont pas tous les mêmes commandes. Il faut absolument que vous fixer vos ips à partir de votre routeur soit votre box internet (le plus souvent).

**Comment by kadmon77** [comment]
Ca y est, je l'ai fait puis mis à jour le plugin et tout semble rentré 
dans l'ordre. A priori, c'est parfait :)

Merci


Le 03/10/2021 à 11:15, Luc Guinchard a écrit :
