### ISSUE TITLE
L’image de mon appareil `RX-S602` n’existe pas.

### ISSUE THREAD

**Issue by OUARZA** [lucguinchard/plugin-Yamaha-musiccast#48]
Bonjour,
voici quelques images.
![image](https://user-images.githubusercontent.com/34892335/140811022-a133607a-fb61-46d9-9903-83cb0a0a8117.png)
![image](https://user-images.githubusercontent.com/34892335/140811049-8a800497-ee96-432f-b131-408a52d93e1d.png)
Merci
Mathieu

**Comment by lucguinchard** [comment]
J'ai ajouté l’image dans le commit suivant : https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/04c651ae5da21751216a470ba97dc789921e1db1

Est-ce que l’image s'affiche proprement ?
