### ISSUE TITLE
L’image de mon appareil `RX-A880` n’existe pas.

### ISSUE THREAD

**Issue by sammtrend** [lucguinchard/plugin-Yamaha-musiccast#50]
Salut,

Je ne crois pas que cette icone existe déjà pour ce modèle. Merci pour le super boulot que tu fais !

![yamaha-rx-a880-front](https://user-images.githubusercontent.com/28105076/144921485-a2996f1b-9e61-4ddd-a4e0-4f64ca1a8a0a.png)

**Comment by lucguinchard** [comment]
Merci à toi

J'ai ajouté l’image dans le commit suivant : [e6087e6](https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/d5992a8e7096c4d5dbc0d99ab854f1fff863b291)

Après mise à jour, est-ce que l’image s'affiche proprement ?

**Comment by sammtrend** [comment]
Salut oui ça fonctionne! Un grand merci !

Le sam. 11 déc. 2021 à 22:45, Luc Guinchard ***@***.***> a
écrit :
