### ISSUE TITLE
L’image de mon appareil `WX-021` n’existe pas.

### ISSUE THREAD

**Issue by sammtrend** [lucguinchard/plugin-Yamaha-musiccast#51]
Avant de valider la demande, merci de vérifier qu’il n’y est pas déjà une demande pour cet appareil.

Salut, voilà une autre demande d'icone pour le WX-021. Encore merci !

![YamahaWX-21](https://user-images.githubusercontent.com/28105076/144922024-9254e9a8-c204-4da5-8441-a5762cc52613.png)
21

**Comment by lucguinchard** [comment]
J'ai ajouté l’image dans le commit suivant : [e6087e6](https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/d5992a8e7096c4d5dbc0d99ab854f1fff863b291)

Après mise à jour, est-ce que l’image s'affiche proprement ?

**Comment by sammtrend** [comment]
Salut Oui ça fonctionne parfaitement bien ! Super ! Merci pour le super
boulot!

Le sam. 11 déc. 2021 à 22:46, Luc Guinchard ***@***.***> a
écrit :

**Comment by sammtrend** [comment]
J'en profite pour te dire que j'ai trouvé une solution qu'il pourrait être
intéressant de documenter dans ton application :
https://community.jeedom.com/t/musiccast-refonte-v4/11043/103
pour les personnes qui ont leur jeedom dans un réseau différent de leurs
enceintes.

**Comment by lucguinchard** [comment]
Merci, je vais regarder comment ajouter cela à documentation.
