### ISSUE TITLE
tuner_set_frequency_direct  impossible de mettre une valeur via un scenario

### ISSUE THREAD

**Issue by Gis70** [lucguinchard/plugin-Yamaha-musiccast#53]
salut,

quand j'appelle tuner_set_frequency_direct  il n'y a pas de champ pour rentrer la valeur dans un scénario.

**Comment by lucguinchard** [comment]
Salut,

J'ai fait une modification dans le commit suivant : 02aa2362e0732ba475da6d62ae924e971e52a963.
Il faut après mettre à jour, refaire une synchro des appareils.

Attention la Fréquence est en kHz et non en mHz (ex: 107700, pour 107.7).

Je ne peux pas testé de mon coté. Est-ce que cela marche chez toi ?

**Comment by Gis70** [comment]
Salut, merci, je regarde ça dans le weekend, oui j'avais testé via une url en direct.  

Je te tiens au courant.

**Comment by Gis70** [comment]
Tuner Set frequency fonctionne, niquel merci (j'avais fait un virtuel en attendant)

**Comment by lucguinchard** [comment]
Merci beaucoup pour le café ;)
