### ISSUE TITLE
L’image de mon appareil `R-N803D` n’existe pas.

### ISSUE THREAD

**Issue by sfingers76** [lucguinchard/plugin-Yamaha-musiccast#55]
Avant de valider la demande, merci de vérifier qu’il n’y est pas déjà une demande pour cet appareil.
![yamrn803dnr,101231-1200px](https://user-images.githubusercontent.com/43130642/148769964-03db88c2-a8d0-45fc-a1ea-d8ee83ad387e.jpg)
SVP

**Comment by lucguinchard** [comment]
J'ai ajouté l’image dans le commit suivant : https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/c8325d7effcb344ef5bfeee33acaca87b895189a

Après mise à jour, est-ce que l’image s'affiche proprement ?
