### ISSUE TITLE
L’image de mon appareil `RX-V4A` n’existe pas.

### ISSUE THREAD

**Issue by DavidB33** [lucguinchard/plugin-Yamaha-musiccast#56]
![rx-v4a](https://user-images.githubusercontent.com/72492486/150163506-58e57a92-d713-4712-9c1f-4065d80a8aba.jpg)
Bonjour,
Je viens d'installer votre plugin et je vous remercie pour le partage de votre travail.
Je viens de m'équiper d'un ampli Yamaha RX-V4A et je n'ai pas de photo de cette équipement. Rien de bien grave en soit, mais j'ai vu qu'on pouvait en faire la demande.
Rien de bien important donc, je vais voir un peu comment utiliser votre plugin.

++
loops

**Comment by lucguinchard** [comment]
J'ai ajouté l’image dans le commit suivant : [c8325d7](https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/85ad05faf94fe7ff0d95d073897a8d0b0e4e2bd7)

Après mise à jour, est-ce que l’image s'affiche proprement ?
