### ISSUE TITLE
Je ne peux plus régler le volume depuis l'interface

### ISSUE THREAD

**Issue by Helikoptere** [lucguinchard/plugin-Yamaha-musiccast#60]
Bonjour, depuis environ 2 mises à jour je ne peux plus régler le volume depuis l'interface, aussi l'image de la station radio ne s'affiche plus 

![image](https://user-images.githubusercontent.com/98903166/152197264-27cdc5d9-a10a-4419-9945-04cc0c83fd5c.png)

Merci pour ce super plugin, bonne journée

**Comment by lucguinchard** [comment]
Bonjour,

Jeedom à fait quelques mises à jours sur le CSS en version `4.2.x`. 
La mise à jour pour adapter le plugin à la 4.2.x a été déployé lundi soir https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/7de27df3947fa59576cf1f7fdde61ad10558c417.
Après chaque mise à jours (plugin ou core), il est conseillé de  rafraîchir le cache (`Ctrl+F5`).

Il reste quelque détail à réaliser, notamment dans la liste des appareils en mode liste. ;)

Bonne journée.
Luc
