### ISSUE TITLE
L’image de mon appareil `R-N602` n’existe pas.

### ISSUE THREAD

**Issue by Helikoptere** [lucguinchard/plugin-Yamaha-musiccast#61]
Bonjour,

Image au format PNG 300*151

Merci
![Yamaha-R-N602-Silver_Fac_600](https://user-images.githubusercontent.com/98903166/152202055-fab5bd52-afaf-4f6a-9b38-63cda97f3b16.png)

**Comment by lucguinchard** [comment]
J'ai ajouté l’image dans le commit suivant : https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/a023027b2060a75692d24c7e12545684e52505fa

Après mise à jour, est-ce que l’image s'affiche proprement ?
