### ISSUE TITLE
L’image de mon appareil `RX-A3060` n’existe pas.

### ISSUE THREAD

**Issue by rubs31** [lucguinchard/plugin-Yamaha-musiccast#63]
Avant de valider la demande, merci de vérifier qu’il n’y est pas déjà une demande pour cet appareil.
![rx-a3060-noir_5a1bf01fa0480_1200](https://user-images.githubusercontent.com/99728881/154083377-f68a5120-1ca7-422c-83b3-4318b4898964.jpg)

Merci pour ce plugin. Je commence les tests, ça se présente bien :-)

**Comment by lucguinchard** [comment]
J'ai ajouté l’image dans le commit suivant : https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/28d70a2df9f3d586609a7ee911b566df5e1cfbfc

Après mise à jour, est-ce que l’image s'affiche proprement ?

**Comment by rubs31** [comment]
Bonsoir.

superbe !



Merci pour ce superbe travail.
Il n’y a qu'un mois que j’utilise jeedom, je suis impressionné par le champ de possibilités qui s’ouvre (j’ai un équipement gce avec pas mal de modules IPX 800 v4 et v5).
Votre plugin va me permettre de mettre mon home cinéma en route automatiquement. Et aussi de mettre en veille le yamaha parce que la veille automatique n’est pas très fiable, et l’ampli consomme énormément à cause de la technologie qu’il utilise.

Vous méritez bien un bon commentaire, et un bon café :-)
Ce que je vais faire tout de suite.
