### ISSUE TITLE
L’image de mon appareil `YSP-2700` n’existe pas.

### ISSUE THREAD

**Issue by Xav-74** [lucguinchard/plugin-Yamaha-musiccast#64]
Hello Luc,

![ysp-2700](https://user-images.githubusercontent.com/56156622/154662195-c057b82d-7ed3-4a7e-832f-cf2fcd41071e.png)

Ci-jointe une image pour ma barre + caisson YSP 2700 ;)
Merci d'avance

**Comment by lucguinchard** [comment]
J'ai ajouté l’image dans le commit suivant : [28d70a2](https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/138e16150efbe1d938972850ed79088b7aac2ede)

Après mise à jour, est-ce que l’image s'affiche proprement ?
