### ISSUE TITLE
L’image de mon appareil `RX-V485` n’existe pas.

### ISSUE THREAD

**Issue by PhilippeMPerso** [lucguinchard/plugin-Yamaha-musiccast#66]
Bonjour,

Super plugin, que j'utilise depuis plusieurs mois dejà ;)

Je vous propose l'image suivante pour mon ampli Yamaha
![image](https://user-images.githubusercontent.com/57010281/160273560-38e2eee6-a08a-41c4-a4a6-2b9bc1299504.png)

**Comment by lucguinchard** [comment]
J'ai ajouté l’image dans le commit suivant : https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/be1ce90e8af24d4b80831cd987235df797cc4c7a

Après mise à jour, est-ce que l’image s'affiche proprement ?

**Comment by PhilippeMPerso** [comment]
Oui, parfait. Merci ;)

**Comment by PhilippeMPerso** [comment]
Par contre, suite à la mise à jour du plugin, mon ampli n'est plus détecté:
![image](https://user-images.githubusercontent.com/57010281/160653077-2704ae80-3320-4c46-91fc-27ecf3402186.png)

**Comment by PhilippeMPerso** [comment]
![image](https://user-images.githubusercontent.com/57010281/160653771-c54da930-545a-4bd6-8001-9d134490e923.png)

Je suis en Jeedom 4.1.28

**Comment by PhilippeMPerso** [comment]
a priori, il s'agit plus d'un problème d'affichage dans les designs, car les commandes (dans des scenarios par exemple) fonctionnent toujours

**Comment by PhilippeMPerso** [comment]
Fausse alerte, je n'avais le problème que dans la session Chrome à partir de laquelle j'ai fait la mise à jour du plugin (étrange quand même)
Je suis allé vider le cache (ctrl+F5 puis suppression des cookies n'ayant pas suffit) et tout est rentré dans l'ordre

**Comment by lucguinchard** [comment]
Oui j'ai réalisé par la suite une grosse mise à jour qui nécessité un `ctrl+F5`. Modification du `css` + `js`.
Il est conseillé de faire ce `ctrl+F5` à chaque mise à jour `core` ou `plugin(s)`.

Je clos le sujet de l’image ;-) .
