### ISSUE TITLE
L’image de mon appareil `NS-NSW100` n’existe pas.

### ISSUE THREAD

**Issue by TanamuR** [lucguinchard/plugin-Yamaha-musiccast#68]
Hello Luc, Je découvre le plugin. Quelques soucis pour remonter ma conf Musiccast. 4 à 5 jours je pense.
Tout est remonté maintenant.
Image du Sub 100 manquante.
Merci pour ton travail.

**Comment by lucguinchard** [comment]
J'ai ajouté l’image dans le commit suivant : f0af57212106d3014918ce323e9f10a4b9deef28

Après mise à jour, est-ce que l’image s'affiche proprement ?

**Comment by TanamuR** [comment]
Bonjour Luc
C'est bon ca marche.
Merci

Le mer. 7 déc. 2022 à 20:46, Luc Guinchard ***@***.***> a
écrit :
