### ISSUE TITLE
Message success en rouge.

### ISSUE THREAD

**Issue by lucguinchard** [lucguinchard/plugin-Yamaha-musiccast#7]
Dans le fichier `YamahaMusiccast.ajax.php` le message success est en rouge :

![image](https://user-images.githubusercontent.com/17431299/73919775-790e6d80-48c4-11ea-95a9-53b1cde83fb7.png)

La modification dépend de  : https://github.com/NextDom/nextdom-core/issues/1692

**Comment by Gis70** [comment]
il faudrait ajouté un refresh de la page aussi pour voir les nouveaux appareils.

**Comment by lucguinchard** [comment]
Suite à la mise à jour du 13 février 2022. Cela est maintenant résolu. Quelqu'un peut confirmer, en `Jeedom 4.2.x` ?
