### ISSUE TITLE
L’image de mon appareil `RX-V481` n’existe pas.

### ISSUE THREAD

**Issue by vallatd** [lucguinchard/plugin-Yamaha-musiccast#70]
Avant de valider la demande, merci de vérifier qu’il n’y est pas déjà une demande pour cet appareil.

Bonjour
veuillez trouver une image du RX-V481
Merci
![RX-V481](https://github.com/lucguinchard/plugin-Yamaha-musiccast/assets/133332109/e8ae9fc6-e1b3-4815-bd7e-b65dc270ded3)

**Comment by lucguinchard** [comment]
J'ai ajouté l’image dans le commit suivant : https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/e6c5221752a3e5fa6c8e86744155ca1725553193

Après mise à jour, est-ce que l’image s'affiche proprement ?
