### ISSUE TITLE
L’image de mon appareil `RX-A4A` n’existe pas.

### ISSUE THREAD

**Issue by chapetois** [lucguinchard/plugin-Yamaha-musiccast#71]
Bonjour,
Pas d' urgence, c'est juste cosmétique.
![image](https://github.com/lucguinchard/plugin-Yamaha-musiccast/assets/70724393/2145ee63-55b0-429f-aaa9-c618d7070737)
Merci

**Comment by lucguinchard** [comment]
J'ai ajouté l’image dans le commit suivant : https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/88e4418015597ba9a3497fec86db710138eb5df8

Après mise à jour, est-ce que l’image s'affiche proprement ?

**Comment by chapetois** [comment]
Bonjour,
Oui l'image s'affiche.
Nickel
Merci
Bon WE
