### ISSUE TITLE
Compatibilité avec Jeedom 4.4 and Debian 12 Bookworm x64

### ISSUE THREAD

**Issue by paifre** [lucguinchard/plugin-Yamaha-musiccast#72]
Bonjour,

J'effectue actuellement une évaluation de la compatibilité de mes plugins avec Jeedom 4.4 sur bookworm dans une VM de test avec PHP8
J'ai le message d'erreur à l'activation du plugin:

[2024-01-18 14:45:31][ERROR] : Erreur sur la fonction deamon_stop du plugin : socket_connect(): Argument #3 ($port) must be of type ?int, string given

Une information liée à la compatibilité PHP8

https://community.jeedom.com/t/aide-rpi-5-debian-12-zwavejs-razberry/115761

Je suis dispo pour d'éventuels tests sur une branche dédiée.
Merci par avance

**Comment by lucguinchard** [comment]
Merci de l'issue.

**Comment by lucguinchard** [comment]
J'ai fais une mise à jour concernant l'erreur sur la branche principale. n'ayant pas de jeedom en php 8.2 je ne peux pas vérifier si il y a d'autre(s) erreur(s).

**Comment by paifre** [comment]
Bonjour,
Je viens de faire le test et la correction fonctionne et permet au plugin de démarrer
Malheureusement, je rencontre un autre problème déjà vu dans la version actuelle que je n'ai pas pris le temps de vous remonter.
J'ouvre une autre issue pour ce problème
