### ISSUE TITLE
Synchroniser -> 500 : Internal Server Error

### ISSUE THREAD

**Issue by paifre** [lucguinchard/plugin-Yamaha-musiccast#73]
Bonjour,

Environnement Debian 12, x86_64, Jeedom 4.4 alpha à jour

Lorsque j'appuie sur "synchroniser", j'ai un message d'alerte Jeedom:  **500 : Internal Server Error**
Presence de ce message dans le fichier de log Jeedom: http.error:
`0262|[Sat Feb 03 11:50:50.533128 2024] [php:error] [pid 26222] [client 127.0.0.1:55758] PHP Fatal error:  Uncaught Error: Using $this when not in object context in /var/www/html/plugins/YamahaMusiccast/core/class/YamahaMusiccast.class.php:490\nStack trace:\n#0 /var/www/html/plugins/YamahaMusiccast/core/class/YamahaMusiccast.class.php(454): YamahaMusiccast::saveDeviceIp()\n#1 /var/www/html/plugins/YamahaMusiccast/core/ajax/YamahaMusiccast.ajax.php(137): YamahaMusiccast::searchAndSaveDeviceList()\n#2 {main}\n  thrown in /var/www/html/plugins/YamahaMusiccast/core/class/YamahaMusiccast.class.php on line 490, referer: http://localhost/index.php?v=d&m=YamahaMusiccast&p=YamahaMusiccast
0263|[Sat Feb 03 11:56:17.127860 2024] [php:error] [pid 26224] [client 127.0.0.1:57906] PHP Fatal error:  Uncaught Error: Using $this when not in object context in /var/www/html/plugins/YamahaMusiccast/core/class/YamahaMusiccast.class.php:490\nStack trace:\n#0 /var/www/html/plugins/YamahaMusiccast/core/class/YamahaMusiccast.class.php(454): YamahaMusiccast::saveDeviceIp()\n#1 /var/www/html/plugins/YamahaMusiccast/core/ajax/YamahaMusiccast.ajax.php(137): YamahaMusiccast::searchAndSaveDeviceList()\n#2 {main}\n  thrown in /var/www/html/plugins/YamahaMusiccast/core/class/YamahaMusiccast.class.php on line 490, referer: http://localhost/index.php?v=d&m=YamahaMusiccast&p=YamahaMusiccast&id=YamahaMusiccast
`
Malgré le niveau Debug dans le plugin, rien d'explicite dans les logs.

![image](https://github.com/lucguinchard/plugin-Yamaha-musiccast/assets/37601174/cc664a37-d10f-45bb-8df4-9d7525bf6b67)

A noter et peut-être un impact:
Le 1er equipement de l'array ([0]) n'est pas un équipement Yamaha MusicCast mais un TV connectée Panasonic, le port d'écoute est potentiellement le même. Peut être un filtre à mettre en place pour ejecter ce qui n'est pas MusicCast

A dispo pour ajouter d'eventuels traces spécifiques

Merci par avance

**Comment by lucguinchard** [comment]
J'ai mis un fix concernant ce problème. Est-ce que c'est mieux après la mise à jour ?

**Comment by paifre** [comment]
Bonjour,

Merci pour ce fix rapide.  L'erreur 500 à disparu. Le scan ne trouve pas les appareils souhaités.

Trois points que j'ai relevé:

1. Le scan semble être plus lent et n'arrive pas à scanner mes deux Musiccast en ip .77 et .75
Une seule fois le scan a atteint la TV Panasonic en .80.  Le scan semble repartir du haut et repasse encore et encore sur les mêmes IP. Voir fichier de log.
D'où le message:
![image](https://github.com/lucguinchard/plugin-Yamaha-musiccast/assets/37601174/a148a867-e28e-4451-9b57-9fd21d250842)

2.  Il y a un message d'erreur à la relance du daemon que j'ai isolé un peu dans la log (ligne 33)
et message
![image](https://github.com/lucguinchard/plugin-Yamaha-musiccast/assets/37601174/9767921c-2805-41b4-8bd6-f521a023b20c)


3. PI, une évolution d'API à envisager pour Jeedom 4.4
![image](https://github.com/lucguinchard/plugin-Yamaha-musiccast/assets/37601174/b070c8a4-136f-4556-b1a9-e883a0747d71)

[YamahaMusiccast.txt](https://github.com/lucguinchard/plugin-Yamaha-musiccast/files/14156572/YamahaMusiccast.txt)

Merci par avance

**Comment by lucguinchard** [comment]
Bonjour,

J'ai corrigé certaines choses suite à tes remarques.
Est-ce que cela marche mieux ?
J'ai aussi ajouté quelques debug lors des ajouts des appareils.

**Comment by paifre** [comment]
Bonjour,
Je viens de faire un 1er test, retour positif :)  C'est top
Peux-tu me confirmer que tu continues de scanner les appareils independamment sur bouton synchroniser, c'est ce qu'il me semble d'après les logs ?
Point 1, 2 et 3 -> a priori OK
Je n'ai pas encore transféré le fichier de log vers notepad++. L'encodage reporté par la VM reste sur unknown 8bit mais pas d'anomalie d'affichage à l'écran des logs jeedom.
J'ai repéré un souci avec la selection de playlist qobuz comme inputs.  Je regarde plus avant

**Comment by lucguinchard** [comment]
Alors quelques petites choses : 
Le plugin ne scan pas régulièrement les nouveaux appareils. Il n'y as pas d’intérêt à faire cela. Par contre il reste en communication non stop avec les appareils connus.

Concernant les problème UTF-8 des fichiers de logs, je pense que cela viens de ta configuration de machine ou d'un problème Jeedom/core.

Aussi le port que tu utilises (le port 9999 par défaut) est aussi le port des appareils Google. d'où les message du type : 
```
Lâappareil 192.168.1.122 dialogue sur le port 9999 avec le message : Ðòøÿ÷Õï¶ÑŽÀìæáèÊðöö
```
Tu as la possibilité de changer le port dans l'administration Jeedom musiccast.

Si tout est bon pour toi tu peux clore le ticket ;)

**Comment by paifre** [comment]
Super. Merci pour ton complément d'info, j'ai effectivement des google cast et home. Je vais tester en décalant le n° de port.
Concernant les logs, c'est bizarre. 50% des logs ne sont pas UTF-8. alors que je suppose que tous le monde utilise l'API log::add('mylogname'..
Je clos ce ticket. Merci encore :)
