### ISSUE TITLE
L’image de mon appareil `RX-V6A` n’existe pas.

### ISSUE THREAD

**Issue by zxdd7525** [lucguinchard/plugin-Yamaha-musiccast#74]
Bonjour Luc,
Voici une photo du RX-V6A.
Merci pour ton travail.

![yamaha-RX-V6A](https://github.com/lucguinchard/plugin-Yamaha-musiccast/assets/144697689/c5f63793-e1ec-47f6-8f6f-74146ced7e51)

**Comment by lucguinchard** [comment]
J'ai ajouté l’image dans le commit suivant : https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/0c6b22de7a067565a9c0dd64aa163beb871097c3

Après mise à jour, est-ce que l’image s'affiche proprement ?

**Comment by zxdd7525** [comment]
Bonjour Luc,
oui c'est tout bon, merci beaucoup.
cdt
PM
