### ISSUE TITLE
L’image de mon appareil `RX-V6A` n’existe pas.

### ISSUE THREAD

**Issue by titour65** [lucguinchard/plugin-Yamaha-musiccast#75]
![rx-v6a](https://github.com/lucguinchard/plugin-Yamaha-musiccast/assets/165400706/0b2b0cea-cd9e-42df-8e11-aa2ef7aa01c1)
Avant de valider la demande, merci de vérifier qu’il n’y est pas déjà une demande pour cet appareil.

**Comment by lucguinchard** [comment]
J'ai ajouté l’image dans le commit suivant : https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/0c6b22de7a067565a9c0dd64aa163beb871097c3

Après mise à jour, est-ce que l’image s'affiche proprement ?

**Comment by titour65** [comment]
Bonjour,

C'est bon, l'image s'affiche proprement, merci !

----- Mail original -----
De: "Luc Guinchard" ***@***.***>
À: "lucguinchard/plugin-Yamaha-musiccast" ***@***.***>
Cc: "titour65" ***@***.***>, "Author" ***@***.***>
Envoyé: Samedi 30 Mars 2024 12:56:52
Objet: Re: [lucguinchard/plugin-Yamaha-musiccast] L’image de mon appareil `RX-V6A` n’existe pas. (Issue #75)





J'ai ajouté l’image dans le commit suivant : 0c6b22d 

Après mise à jour, est-ce que l’image s'affiche proprement ?
