### ISSUE TITLE
L’image de mon appareil `RX-A2080` n’existe pas.

### ISSUE THREAD

**Issue by FredVeron08** [lucguinchard/plugin-Yamaha-musiccast#76]
Avant de valider la demande, merci de vérifier qu’il n’y est pas déjà une demande pour cet appareil.

**Comment by lucguinchard** [comment]
J'ai ajouté l’image dans le commit suivant : https://github.com/lucguinchard/plugin-Yamaha-musiccast/commit/d6b26ef7e3dadc31f3651b5cdada0ea51e8f8a14

Après mise à jour, est-ce que l’image s'affiche proprement ?
