### ISSUE TITLE
Mise en forme du template.

### ISSUE THREAD

**Issue by lucguinchard** [lucguinchard/plugin-Yamaha-musiccast#8]
Le Template actuel est sommaire (moche).
Un travail sera fait prochainement.
Pour toute suggestion : go to comment.

**Comment by zz2021top** [comment]
Bonjour,
j'avais l'ancien plugins Musiccast qui ne fonctionne malheureusement plus. Je suis absolument ravi du plugin que vous avez créé. Il fonctionne bien sur mon RXAS710D. J'aurais cependant une suggestion. Il ne vois pas mes radio favorites (FM et DAB), il voit cependant bien mes radios internet.
Si vous avez besoins d'infos supplémentaire, j'essayerai de vous aider avec mes moyens limités.
Encore merci pour ce gros travail
